//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Balance()
        {
            this.Balance1 = new HashSet<Balance>();
            this.DeletedTransactionDetails = new HashSet<DeletedTransactionDetail>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FinanceCycleId { get; set; }
        public Nullable<decimal> Credint { get; set; }
        public Nullable<decimal> ActualExchange { get; set; }
        public Nullable<decimal> RelativeDeviation { get; set; }
        public Nullable<decimal> DeviationRatio { get; set; }
        public Nullable<int> AccountTreeId { get; set; }
        public Nullable<decimal> Retainer { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> BalanceId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance> Balance1 { get; set; }
        public virtual Balance Balance2 { get; set; }
        public virtual FinancialCycle FinancialCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedTransactionDetail> DeletedTransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
