//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.Checks = new HashSet<Check>();
            this.PrintChecks = new HashSet<PrintCheck>();
            this.TransactionRecipients = new HashSet<TransactionRecipient>();
        }
    
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> BankAccountTypeId { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public Nullable<int> AccountSubId { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string BankLabel { get; set; }
        public string IBan { get; set; }
        public string FirstSignature { get; set; }
        public string SecondSignature { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AccountSub AccountSub { get; set; }
        public virtual BankAccountType BankAccountType { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Checks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintCheck> PrintChecks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRecipient> TransactionRecipients { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
