//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circu
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> CircusDate { get; set; }
        public string FNo { get; set; }
        public string Subject { get; set; }
        public Nullable<int> DepartmentSenderId { get; set; }
        public Nullable<int> DepartmentRecipientId { get; set; }
        public string DepartmentSenderName { get; set; }
        public string DepartmentRecipientName { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string ReceiverEmployeeName { get; set; }
        public string Signatur { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
