//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMember
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> CommitteeJobId { get; set; }
        public Nullable<int> CommitteeFormationId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CommitteeJob CommitteeJob { get; set; }
        public virtual CommitteFormation CommitteFormation { get; set; }
    }
}
