//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetingCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompetingCompany()
        {
            this.GeneralConditionEvaluations = new HashSet<GeneralConditionEvaluation>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyRegisterationId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CommitteeFormationId { get; set; }
        public Nullable<int> AccountTreeId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CommitteFormation CommitteFormation { get; set; }
        public virtual CompanyRegisteration CompanyRegisteration { get; set; }
        public virtual AccountTree AccountTree { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralConditionEvaluation> GeneralConditionEvaluations { get; set; }
    }
}
