//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDocument
    {
        public int Id { get; set; }
        public Nullable<int> CompanyRegisterationId { get; set; }
        public string ImagePath { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CompanyRegisteration CompanyRegisteration { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
