//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeletedTransaction()
        {
            this.DeletedTransactionDetails = new HashSet<DeletedTransactionDetail>();
        }
    
        public int Id { get; set; }
        public int DocumentTypeId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> FinancialCycleId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Recipient { get; set; }
        public Nullable<bool> HasAddedTax { get; set; }
        public Nullable<bool> HasTax { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string CheckNo { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual FinancialCycle FinancialCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedTransactionDetail> DeletedTransactionDetails { get; set; }
    }
}
