//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedTransactionDetail
    {
        public int Id { get; set; }
        public int DeletedTransactionId { get; set; }
        public int AccTreeId { get; set; }
        public Nullable<int> BalanceId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> TransactionDetailId { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        public virtual Balance Balance { get; set; }
        public virtual DeletedTransaction DeletedTransaction { get; set; }
    }
}
