//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialCycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialCycle()
        {
            this.Balances = new HashSet<Balance>();
            this.OpeningBalances = new HashSet<OpeningBalance>();
        }
    
        public int Id { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Credint { get; set; }
        public Nullable<decimal> ActualExchange { get; set; }
        public Nullable<decimal> RelativeDeviation { get; set; }
        public Nullable<decimal> RelativeRatio { get; set; }
        public Nullable<bool> CurrentYear { get; set; }
        public Nullable<bool> IsClosed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Balance> Balances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpeningBalance> OpeningBalances { get; set; }
    }
}
