//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialCycleAccountTree
    {
        public int Id { get; set; }
        public Nullable<int> AccTreeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> FinancialCycleId { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        public virtual AccountTree AccountTree1 { get; set; }
        public virtual FinancialCycle FinancialCycle { get; set; }
    }
}
