//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralConditionEvaluation
    {
        public int Id { get; set; }
        public Nullable<int> CompetingCompanyId { get; set; }
        public Nullable<int> GeneralConditionId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CompetingCompany CompetingCompany { get; set; }
        public virtual GeneralCondition GeneralCondition { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
