//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceImage
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<bool> IsChoosed { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
