//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemDetailUnit
    {
        public int Id { get; set; }
        public Nullable<int> ItemDetailId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> EqualFromMini { get; set; }
        public Nullable<bool> IsMini { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
