//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEnteryDetail
    {
        public int Id { get; set; }
        public Nullable<int> JournalEnteryId { get; set; }
        public Nullable<int> AccTrreId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> IsCredit { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        public virtual JournalEntery JournalEntery { get; set; }
    }
}
