//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Circu> Circus { get; set; }
        public virtual DbSet<CommitteeJob> CommitteeJobs { get; set; }
        public virtual DbSet<CommitteeMember> CommitteeMembers { get; set; }
        public virtual DbSet<CommitteeType> CommitteeTypes { get; set; }
        public virtual DbSet<CommitteFormation> CommitteFormations { get; set; }
        public virtual DbSet<CompanyDocument> CompanyDocuments { get; set; }
        public virtual DbSet<CompanyRegisteration> CompanyRegisterations { get; set; }
        public virtual DbSet<CompetingCompany> CompetingCompanies { get; set; }
        public virtual DbSet<GeneralCondition> GeneralConditions { get; set; }
        public virtual DbSet<GeneralConditionEvaluation> GeneralConditionEvaluations { get; set; }
        public virtual DbSet<TechnicalCondition> TechnicalConditions { get; set; }
        public virtual DbSet<TechnicalConditionEvaluation> TechnicalConditionEvaluations { get; set; }
        public virtual DbSet<Tender> Tenders { get; set; }
        public virtual DbSet<AccountFinal> AccountFinals { get; set; }
        public virtual DbSet<AccountNature> AccountNatures { get; set; }
        public virtual DbSet<AccountSub> AccountSubs { get; set; }
        public virtual DbSet<AccountSubCategory> AccountSubCategories { get; set; }
        public virtual DbSet<AccountTree> AccountTrees { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<Balance> Balances { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<BankAccountType> BankAccountTypes { get; set; }
        public virtual DbSet<Check> Checks { get; set; }
        public virtual DbSet<DeletedTransaction> DeletedTransactions { get; set; }
        public virtual DbSet<DeletedTransactionDetail> DeletedTransactionDetails { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<FinancialCycle> FinancialCycles { get; set; }
        public virtual DbSet<FinancialCycleAccountTree> FinancialCycleAccountTrees { get; set; }
        public virtual DbSet<OpeningBalance> OpeningBalances { get; set; }
        public virtual DbSet<OpeningBalanceDetail> OpeningBalanceDetails { get; set; }
        public virtual DbSet<PrintCheck> PrintChecks { get; set; }
        public virtual DbSet<Receipt> Receipts { get; set; }
        public virtual DbSet<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual DbSet<ReceiptType> ReceiptTypes { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<TransactionRecipient> TransactionRecipients { get; set; }
        public virtual DbSet<Vat> Vats { get; set; }
        public virtual DbSet<CurrencyDetail> CurrencyDetails { get; set; }
        public virtual DbSet<CurrencyType> CurrencyTypes { get; set; }
        public virtual DbSet<InvoiceImage> InvoiceImages { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemDetail> ItemDetails { get; set; }
        public virtual DbSet<ItemDetailUnit> ItemDetailUnits { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetiail> OrderDetiails { get; set; }
        public virtual DbSet<OrderImage> OrderImages { get; set; }
        public virtual DbSet<OrderType> OrderTypes { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<UserWorkDetail> UserWorkDetails { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> GetLastAccNumber(Nullable<int> accParentId)
        {
            var accParentIdParameter = accParentId.HasValue ?
                new ObjectParameter("AccParentId", accParentId) :
                new ObjectParameter("AccParentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetLastAccNumber", accParentIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SpLastLevel(string accCode)
        {
            var accCodeParameter = accCode != null ?
                new ObjectParameter("AccCode", accCode) :
                new ObjectParameter("AccCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SpLastLevel", accCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SpLastTreeAccountId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SpLastTreeAccountId");
        }
    }
}
