//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetiail
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ItemDetialId { get; set; }
        public Nullable<int> RequierCount { get; set; }
        public Nullable<int> ApproveCount { get; set; }
        public Nullable<int> ReceiveCount { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemDetail ItemDetail { get; set; }
        public virtual Order Order { get; set; }
    }
}
