//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Circus = new HashSet<Circu>();
            this.CommitteFormations = new HashSet<CommitteFormation>();
            this.CompetingCompanies = new HashSet<CompetingCompany>();
            this.Tenders = new HashSet<Tender>();
            this.InvoiceImages = new HashSet<InvoiceImage>();
            this.OrderDetiails = new HashSet<OrderDetiail>();
            this.OrderImages = new HashSet<OrderImage>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<decimal> SuggestPrice { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> PriceWithVat { get; set; }
        public Nullable<int> VatId { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Circu> Circus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommitteFormation> CommitteFormations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompetingCompany> CompetingCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tender> Tenders { get; set; }
        public virtual Vat Vat1 { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceImage> InvoiceImages { get; set; }
        public virtual OrderType OrderType { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetiail> OrderDetiails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderImage> OrderImages { get; set; }
    }
}
