//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintCheck
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<int> CheckId { get; set; }
        public Nullable<int> CheckType { get; set; }
        public Nullable<int> PayNo { get; set; }
        public Nullable<int> CheckNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Recipient { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual Check Check { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
