//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AccTreeId { get; set; }
        public Nullable<int> ReceiptTypeId { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string RefNumber { get; set; }
        public string RefName { get; set; }
        public string ReceiptNot { get; set; }
        public string Recipient { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<bool> Susppend { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual ReceiptType ReceiptType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
