//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDetail
    {
        public int Id { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<int> AccTreeId { get; set; }
        public Nullable<int> CurrencyTypeId { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Statement { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
    
        public virtual AccountTree AccountTree { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
