//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.PrintChecks = new HashSet<PrintCheck>();
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.TransactionRecipients = new HashSet<TransactionRecipient>();
        }
    
        public int Id { get; set; }
        public int DocumentTypeId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsPosted { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<int> FinancialCycleId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Recipient { get; set; }
        public Nullable<bool> HasAddedTax { get; set; }
        public Nullable<decimal> AddedTaxPercent { get; set; }
        public Nullable<bool> HasTax { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatingDate { get; set; }
        public Nullable<int> CompanyInfoId { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual FinancialCycle FinancialCycle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrintCheck> PrintChecks { get; set; }
        public virtual Recipient Recipient1 { get; set; }
        public virtual CurrencyType CurrencyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionRecipient> TransactionRecipients { get; set; }
        public virtual CompanyInfo CompanyInfo { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
