//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Purchases.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionRecipient
    {
        public int Id { get; set; }
        public string RecipientName { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
